# Generated by Django 5.2.16 on 2026-07-09 12:10

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Project",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("modified", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=200)),
                ("description", models.TextField(blank=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("on_hold", "On hold"),
                            ("completed", "Completed"),
                            ("archived", "Archived"),
                        ],
                        default="active",
                        max_length=20,
                    ),
                ),
            ],
            options={
                "ordering": ["-created"],
                "abstract": False,
                "indexes": [
                    models.Index(
                        fields=["-created"], name="projects_pr_created_5ace3f_idx"
                    ),
                    models.Index(
                        fields=["status", "-created"],
                        name="projects_pr_status_1d86dd_idx",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="Task",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("modified", models.DateTimeField(auto_now=True)),
                ("title", models.CharField(max_length=255)),
                ("assignee", models.CharField(blank=True, max_length=150)),
                (
                    "priority",
                    models.PositiveSmallIntegerField(
                        choices=[
                            (1, "Low"),
                            (2, "Medium"),
                            (3, "High"),
                            (4, "Critical"),
                        ],
                        db_index=True,
                        default=2,
                    ),
                ),
                ("due_date", models.DateField(blank=True, null=True)),
                ("is_complete", models.BooleanField(default=False)),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tasks",
                        to="projects.project",
                    ),
                ),
            ],
            options={
                "ordering": ["-created"],
                "abstract": False,
                "indexes": [
                    models.Index(
                        fields=["-created"], name="projects_ta_created_7f8e37_idx"
                    ),
                    models.Index(
                        fields=["project", "is_complete"],
                        name="projects_ta_project_d5fdad_idx",
                    ),
                ],
            },
        ),
    ]
