# Generated by Django 5.2.16 on 2026-07-09 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0001_initial"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="project",
            constraint=models.UniqueConstraint(
                fields=("name",), name="project_name_unique"
            ),
        ),
    ]
